(() => {
'use strict';
const data=window.CAPA_DATA, $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’'\-·×]/g,' ').replace(/\s+/g,' ').trim();
const search=$('search'),domain=$('domain'),results=$('results'),detail=$('detail');
const oils=new Map(data.oils.map(o=>[o.id,o]));
let selected=oils.has(location.hash.slice(1))?location.hash.slice(1):'lavande-vraie',view='all',risk='',evidenceFilter='',timer;
let favorites=new Set();
try { const saved=JSON.parse(localStorage.getItem('capa-favorites')||'[]'); if(Array.isArray(saved))favorites=new Set(saved.filter(id=>oils.has(id))); } catch(_) {}
function announce(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('visible'),2500);}
function saveFavorites(){try{localStorage.setItem('capa-favorites',JSON.stringify([...favorites]));return true;}catch(_){return false;}}
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');
$('total').textContent=data.oils.length;
$('indication-count').textContent=data.oils.filter(o=>o.evidenceDomains?.length).length;
$('dose-count').textContent=data.oils.filter(o=>o.verifiedRegimens?.length||o.canadaTopical).length;
$('coverage').innerHTML=`<p>${esc(data.coverage?.note||'Inventaire en cours.')}</p><ul>${(data.coverage?.courses||[]).map(c=>`<li><a href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${esc(c.title)}</a> · ${esc(c.pagesRead)} · ${esc(c.status)}</li>`).join('')}</ul>`;
[...new Set(data.oils.flatMap(o=>o.domains))].sort((a,b)=>a.localeCompare(b,'fr')).forEach(d=>{const option=document.createElement('option');option.value=d;option.textContent=d;domain.append(option);});
const searchable=new Map(data.oils.map(o=>[o.id,norm([o.name,o.botanical,...o.aliases,o.chemotype||'',...o.components,...o.domains,o.courseSummary,o.safetyNotice?.text||'',...(o.verifiedUses||[]).flatMap(u=>[u.label,u.context,u.level]),...(o.canadaUses||[]).map(u=>u.label),...(o.courseUses||[]).map(u=>u.label),...(o.clinicalStudies||[]).flatMap(x=>[x.indication,x.population,x.route,x.preparation,x.protocol,x.result]),...(o.verifiedRegimens||[]).flatMap(r=>[r.indication,r.route,r.dose,r.population]),...(o.studiedAssociations||[]).flatMap(a=>[a.title,a.context,a.preparation,a.studiedDose]),...['contraindications','precautions','adverseEffects','interactions','evidence'].flatMap(k=>o[k].map(f=>f.text)),...o.reviewNotes].join(' '))]));
function sourceLink(id,page){const s=data.sources[id];if(!s)return '';const pdfPage=page&&Number.isInteger(Number(page))&&/\.pdf(?:$|[?#])/i.test(s.url);const url=pdfPage?s.url.split('#')[0]+'#page='+encodeURIComponent(page):s.url;return `<a class="source-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer" aria-label="Source : ${esc(s.title)}${page?' · page '+esc(page):''}">${id.startsWith('hippocratus')?'Cours':id.startsWith('ema')?'EMA':id.startsWith('hc-')?'Santé Canada':id.startsWith('kew')?'Kew':id.startsWith('anses')?'Anses':id.startsWith('trial-')?'Essai':'Source'}${page?' · p. '+esc(page):''} ↗</a>`;}
function facts(items){return items.length?`<ul class="facts">${items.map(f=>`<li>${esc(f.text)} ${sourceLink(f.source,f.page)}</li>`).join('')}</ul>`:'<p class="unknown">À documenter.<small>Une information manquante ne signifie pas une absence de risque.</small></p>';}
function verifiedUses(o){const uses=o.verifiedUses||[];return uses.length?`<div class="verified-uses" aria-label="Usages évalués par l’EMA">${uses.map(u=>`<article class="use-card"><span class="use-level ${u.level==='Usage bien établi'?'established':'traditional'}">${esc(u.level)}</span><h4>${esc(u.label)}</h4><p>${esc(u.context)}</p>${sourceLink(u.source)}</article>`).join('')}</div><p class="reading-note">Ces conclusions de l’EMA concernent des médicaments et des préparations définis, selon une voie précise. Elles ne valent pas pour toute huile essentielle du commerce.</p>`:'';}
function canadaUses(o){const uses=o.canadaUses||[];return uses.length?`<div class="verified-uses" aria-label="Allégations d’aromathérapie de Santé Canada">${uses.map(u=>`<article class="use-card canada-use"><span class="use-level">Allégation prévue · Canada</span><h4>${esc(u.label)}</h4><p>Voie ${esc(u.route)} · sous les conditions de la monographie.</p>${sourceLink(u.source,u.page)}</article>`).join('')}</div><p class="reading-note">La monographie de Santé Canada prévoit ces formulations pour des demandes de licence de produits de santé naturels. Elle ne démontre pas à elle seule une efficacité clinique pour un flacon quelconque.</p>`:'';}
function courseUses(o){const uses=o.courseUses||[];return uses.length?`<div class="course-uses" aria-label="Pistes relevées dans les cours">${uses.map(u=>`<article class="course-use"><span class="course-tag">Mention du cours · à recouper</span><h4>${esc(u.label)}</h4>${sourceLink(u.source,u.page)}</article>`).join('')}</div><p class="reading-note">Ces mentions montrent le contenu du cours. Elles ne prouvent pas une efficacité clinique et ne définissent ni une voie, ni une dose.</p>`:'';}
function clinicalStudies(o){const studies=o.clinicalStudies||[];return studies.length?`<div class="clinical-studies" aria-label="Essais cliniques exploratoires">${studies.map(x=>`<article class="clinical-study"><span class="study-level">Essai clinique · résultat à confirmer</span><h4>${esc(x.indication)}</h4><p><strong>Personnes étudiées :</strong> ${esc(x.population)}</p><p><strong>Voie et préparation :</strong> ${esc(x.route)} · ${esc(x.preparation)}</p><p><strong>Protocole de l’essai :</strong> ${esc(x.protocol)}</p><p><strong>Résultat :</strong> ${esc(x.result)}</p><p class="study-limit"><strong>Portée :</strong> ${esc(x.limit)}</p>${sourceLink(x.source)}</article>`).join('')}</div><p class="reading-note">Ces études isolées décrivent une préparation et un contexte précis. Leurs protocoles ne sont pas des posologies à appliquer soi-même.</p>`:'';}
function regimens(o){
 const items=o.verifiedRegimens||[];
 const research=o.doseResearch;
 const hc=o.canadaTopical;
 const missing=`<p class="unknown">Aucune dose exploitable n’a été retenue pour cette huile dans le carnet.<small>La voie et la quantité doivent être liées à une préparation identifiée ; ne pas déduire une dose d’une autre huile ou d’un autre extrait.</small></p>${research?`<aside class="dose-research"><strong>Pourquoi la dose reste à établir</strong><p>${esc(research.text)}</p>${sourceLink(research.source)}</aside>`:''}`;
 return `<section class="regimens" id="voies" aria-labelledby="regimens-title"><p class="section-kicker">VOIES ET DOSES</p><h3 id="regimens-title">${items.length||hc?'Ce que précisent les monographies':'Où en est la vérification ?'}</h3>${items.length?`<p class="reading-note">Repères documentaires EMA pour les médicaments et préparations définis ci-dessous, pas une posologie pour un flacon du commerce. Vérifier la notice du produit et la situation individuelle avant tout emploi.</p><div class="regimen-grid">${items.map(r=>`<article class="regimen-card"><span class="regimen-route">${esc(r.route)} · EMA</span><h4>${esc(r.indication)}</h4><p><strong>Population :</strong> ${esc(r.population)}</p><p><strong>Préparation :</strong> ${esc(r.preparation)}</p><p><strong>Dose de la monographie :</strong> ${esc(r.dose)}</p>${r.limit?`<p><strong>Limite :</strong> ${esc(r.limit)}</p>`:''}${sourceLink(r.source,r.page)}</article>`).join('')}</div>`:''}${hc?`<p class="reading-note">Santé Canada : quantités destinées à l’étiquetage de produits conformes. Usage externe et occasionnel, adultes seulement ; la monographie exclut grossesse et allaitement, et demande un avis médical préalable en cas d’asthme ou d’épilepsie. Elle ne décrit pas la diffusion par nébuliseur. ${sourceLink(hc.source,20)}</p><div class="regimen-grid"><article class="regimen-card canada-dose"><span class="regimen-route">Application cutanée · Canada</span><h4>Concentration du produit fini</h4><p><strong>Population :</strong> ${esc(hc.population)}</p><p><strong>Préparation :</strong> ${esc(hc.preparation)}</p><p><strong>Massage corporel :</strong> ${esc(hc.massage)} d’HE après dilution, sur plus de 10 % de la surface du corps.</p><p><strong>Application locale :</strong> ${esc(hc.local)} d’HE après dilution, sur 10 % ou moins de la surface du corps.</p><p><strong>Cadence de la monographie :</strong> massage une fois par jour ; application locale une à trois fois par jour. Usage occasionnel seulement.</p>${sourceLink(hc.source,hc.page)}</article>${o.canadaInhalation?`<article class="regimen-card canada-dose"><span class="regimen-route">Inhalation · Canada</span><h4>Voies décrites dans la monographie</h4><p><strong>Sur mouchoir :</strong> ${esc(o.canadaInhalation.tissue)}.</p><p><strong>Au-dessus d’eau chaude :</strong> ${esc(o.canadaInhalation.steam)}.</p><p>Ces modalités d’étiquetage ne décrivent pas une nébulisation et ne sont pas interchangeables avec celle-ci.</p>${sourceLink(o.canadaInhalation.source,o.canadaInhalation.page)}</article>`:''}</div>`:''}${!items.length&&!hc?missing:''}</section>`;
}
function associations(o){const items=o.studiedAssociations||[];return items.length?`<section class="associations" id="associations" aria-labelledby="associations-title"><p class="section-kicker">ASSOCIATIONS ÉTUDIÉES</p><h3 id="associations-title">Ce qui a été testé ensemble</h3><p class="reading-note">Une étude portant sur un produit combiné ne valide pas un mélange fait maison ni les mêmes doses pour des huiles prises séparément.</p><div class="association-grid">${items.map(a=>`<article class="association-card"><span class="association-tag">Essai clinique · préparation fixe</span><h4>${esc(a.title)}</h4><p>${esc(a.context)}</p><p><strong>Préparation étudiée :</strong> ${esc(a.preparation)}</p><p><strong>Quantité utilisée dans l’essai :</strong> ${esc(a.studiedDose)}</p><p><strong>Résultat observé :</strong> ${esc(a.finding)}</p><p class="association-limit"><strong>Limite :</strong> ${esc(a.limit)}</p><button type="button" class="association-open" data-open-oil="${esc(a.partnerId)}">Voir la fiche ${esc(oils.get(a.partnerId)?.name||'associée')} →</button>${sourceLink(a.source,a.page)}</article>`).join('')}</div></section>`:'';}
function safetyNotice(o){const note=o.safetyNotice;return note?`<aside class="safety-notice" role="note"><strong>Point de vigilance documentaire</strong><p>${esc(note.text)}</p>${sourceLink(note.source)}</aside>`:'';}
function status(o){return o.canadaExclusion?'Restriction canadienne · voir les conditions':o.verifiedUses?.length?'Usage EMA · préparation définie':o.canadaUses?.length?'Allégation d’aromathérapie · Santé Canada':o.clinicalStudies?.length?'Essai clinique exploratoire · lire le résultat':o.status==='institutional'?'Fiche institutionnelle · à relire':o.status==='partial'?'Sources recoupées en partie · à relire':'Synthèse du cours · à recouper';}
function art(o){return `assets/plantes/${o.art}.webp`;}
const isNew=o=>o.status==='institutional'||Boolean(o.collection);
document.querySelector('[data-view="new"] span').textContent=data.oils.filter(isNew).length;
function riskOverview(o){const categories=[['skin','✋','Peau & muqueuses'],['allergy','✳','Allergies'],['lungs','🫁','Poumons & bronches'],['liver','◈','Foie & voies biliaires'],['kidney','◉','Reins'],['bleeding','🩸','Coagulation & traitements'],['neuro','🧠','Système nerveux']];return `<section class="risk-overview" aria-labelledby="risk-heading"><p class="section-kicker">LES REPÈRES VISUELS</p><h3 id="risk-heading">La vigilance, en un regard</h3><p class="reading-note">Un signal indique une précaution documentée, sans mesurer la gravité. « À documenter » ne signifie jamais « sans risque ».${o.safetyNotice?' Une alerte documentaire distincte figure plus haut dans cette fiche.':''}</p><div class="risk-grid">${categories.map(([key,icon,label])=>{const r=o.riskSignals?.[key];return `<article class="risk-card ${r?'known':'unknown-risk'}"><div class="risk-title"><span class="risk-icon" aria-hidden="true">${icon}</span><h4>${label}</h4></div><span class="risk-status">${r?'Vigilance signalée':'À documenter'}</span><p class="risk-description">${r?esc(r.text):'Évaluation spécifique encore manquante dans cette fiche.'}</p>${r?sourceLink(r.source,r.page):''}</article>`}).join('')}</div></section>`;}
function quickRead(o){
 const u=o.verifiedUses?.[0]||o.canadaUses?.[0]||o.clinicalStudies?.[0]||o.courseUses?.[0];
 const level=o.verifiedUses?.length?'Usage évalué par l’EMA':o.canadaUses?.length?'Allégation prévue par la monographie canadienne':o.clinicalStudies?.length?'Essai clinique exploratoire · à confirmer':o.courseUses?.length?'Piste citée dans le cours · à recouper':'Indication à documenter';
 const use=u?.label||u?.indication||'Aucune indication propre à cette huile encore étayée';
 const routes=[...new Set((o.verifiedRegimens||[]).map(r=>r.route))];
 const route=routes.length?routes.join(' · '):o.canadaUses?.length?(o.canadaInhalation?'Cutanée · inhalation':'Cutanée'):o.clinicalStudies?.length?o.clinicalStudies[0].route:'Voie d’emploi à vérifier pour ce produit';
 const doseHref=o.verifiedRegimens?.length||o.canadaTopical?'#voies':o.clinicalStudies?.length?'#essentiel':'#voies';
 const dose=o.verifiedRegimens?.length?`${o.verifiedRegimens.length} repère${o.verifiedRegimens.length>1?'s':''} EMA pour des préparations définies`:o.canadaTopical?`Concentrations cutanées${o.canadaInhalation?' et quantités d’inhalation':''} de Santé Canada`:o.clinicalStudies?.length?'Protocole d’essai décrit ; pas de posologie validée':'Aucune dose retenue à ce stade';
 const warning=o.canadaExclusion?.text||o.safetyNotice?.text||o.contraindications?.[0]?.text||o.adverseEffects?.[0]?.text||o.precautions?.[0]?.text||'Sécurité spécifique encore incomplète ; lire les vigilances avant toute utilisation.';
 return `<section class="quick-read" aria-label="L’essentiel en un regard"><p class="section-kicker">EN UN REGARD</p><div class="quick-grid"><a href="#essentiel" class="quick-card quick-use"><span>Pour quoi ?</span><strong>${esc(use)}</strong><small>${esc(level)}</small></a><a href="#voies" class="quick-card"><span>Quelle voie ?</span><strong>${esc(route)}</strong><small>Selon la préparation et la personne</small></a><a href="${doseHref}" class="quick-card"><span>Quelle quantité ?</span><strong>${esc(dose)}</strong><small>Voir les conditions d’emploi</small></a><a href="#vigilance" class="quick-card quick-alert"><span>À surveiller</span><strong>${esc(warning)}</strong><small>Lire toutes les précautions</small></a></div></section>`;
}
function date(s){return (s||'').split('-').reverse().join('/');}
function updateHash(){try{history.replaceState(null,'',location.pathname+location.search+(selected?'#'+selected:''));}catch(_){}}
function filtered(){const words=norm(search.value).split(' ').filter(Boolean);return data.oils.filter(o=>(!risk||Boolean(o.riskSignals?.[risk]))&&(!evidenceFilter||(evidenceFilter==='indication'&&Boolean(o.evidenceDomains?.length))||(evidenceFilter==='dose'&&Boolean(o.verifiedRegimens?.length||o.canadaTopical)))&&(!domain.value||(evidenceFilter?o.evidenceDomains||[]:o.domains).includes(domain.value))&&(view!=='favorites'||favorites.has(o.id))&&(view!=='new'||isNew(o))&&words.every(w=>searchable.get(o.id).includes(w)));}
function showDetail(o){
 detail.classList.remove('sources-visible');
 if(!o){detail.innerHTML='<div class="empty-detail"><p class="eyebrow">UNE AUTRE PISTE ?</p><h2>Aucune fiche pour cette sélection.</h2><p>Essayez un autre mot, élargissez le domaine ou retrouvez tout l’herbier.</p><button type="button" data-reset>Voir tout l’herbier</button></div>';return;}
 const isFavorite=favorites.has(o.id);
 detail.innerHTML=`<div class="detail-top"><div class="detail-meta"><span class="label">${status(o)}</span><button class="favorite" type="button" id="favorite" aria-pressed="${isFavorite}" aria-label="${isFavorite?'Retirer':'Ajouter'} ${esc(o.name)} ${isFavorite?'des':'aux'} favoris"><span aria-hidden="true">${isFavorite?'★':'☆'}</span>${isFavorite?'Dans mes favoris':'Garder en favori'}</button></div>
 <div class="plant-heading"><div><h2 tabindex="-1" id="oil-title">${esc(o.name)}</h2><p class="latin">${esc(o.botanical)}</p><div class="domains">${o.domains.map(d=>`<span class="chip">${esc(d)}</span>`).join('')}</div></div><figure class="plant-figure"><img src="${art(o)}" alt="Illustration artistique de ${esc(o.botanical)}" width="1280" height="1280"><figcaption>Illustration artistique</figcaption></figure></div>
 <dl class="identity"><div><dt>Famille</dt><dd>${esc(o.family)}${o.identitySource?' '+sourceLink(o.identitySource):''}</dd></div><div><dt>Partie utilisée</dt><dd>${esc(o.part)}</dd></div><div><dt>Chémotype</dt><dd>${esc(o.chemotype||'Non précisé')}</dd></div></dl></div>
 <nav class="detail-nav" aria-label="Dans cette fiche"><a href="#essentiel">L’essentiel</a><a href="#voies">Voies & doses</a>${o.studiedAssociations?.length?'<a href="#associations">Associations</a>':''}<a href="#vigilance">Vigilance</a><button type="button" class="source-toggle" aria-expanded="false" aria-controls="sources">Afficher les sources</button></nav>
 <div class="detail-body">${quickRead(o)}<section class="course-box" id="essentiel"><p class="section-kicker">LES USAGES DOCUMENTÉS</p><h3>Ce qu’en disent les sources</h3>${safetyNotice(o)}${o.canadaExclusion?`<aside class="safety-notice" role="note"><strong>Restriction canadienne à connaître</strong><p>${esc(o.canadaExclusion.text)}</p>${sourceLink(o.canadaExclusion.source,o.canadaExclusion.page)}</aside>`:''}<p class="course-summary">${esc(o.courseSummary)} ${sourceLink(o.summarySource,(o.summarySource||'').startsWith('hippocratus')?o.coursePage:null)}</p>${verifiedUses(o)}${canadaUses(o)}${clinicalStudies(o)}${courseUses(o)}<p class="reading-note">Les domaines cités sont des repères de recherche, pas des indications personnelles de traitement.</p></section>
 ${regimens(o)}
 ${associations(o)}
 <section><h3>Repères de composition</h3>${o.components.length?`<div class="components">${o.components.map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div><p class="reading-note">Composants cités dans ${(o.componentSource||'hippocratus').startsWith('hippocratus')?'le cours':'la référence citée'} ${sourceLink(o.componentSource||'hippocratus')} · La composition du produit reste à vérifier.</p>`:'<p class="unknown">Composition détaillée à documenter dans cette fiche.</p>'}</section>
 ${riskOverview(o)}
 <section class="safety" id="vigilance"><p class="section-kicker">À LIRE AVANT TOUTE UTILISATION</p><h3>Les points de vigilance</h3><div class="general-safety"><strong>Pour toute huile essentielle</strong><p>Vérifier l’espèce, la partie utilisée, la composition et la destination du produit ; garder les flacons hors de portée des enfants. L’Anses recommande de demander conseil à un professionnel de santé avant tout usage et de contacter un centre antipoison en cas d’exposition accidentelle ou de surdosage. ${sourceLink('anses-vigilance-2024')}</p></div><div class="safety-grid"><section><h4>Contre-indications</h4>${facts(o.contraindications)}</section><section><h4>Précautions</h4>${facts(o.precautions)}</section><section><h4>Effets indésirables</h4>${facts(o.adverseEffects)}</section><section><h4>Interactions</h4>${facts(o.interactions)}</section></div><details class="review" open><summary>Limites de cette fiche & points à relire</summary><ul>${o.reviewNotes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></details></section>
 <section class="discovery-note"><h3>Le petit repère botanique</h3><p>${esc(o.discovery)}</p></section>
 <section class="evidence"><h3>Quel niveau de preuve ?</h3>${o.evidence.length?facts(o.evidence):o.canadaUses?.length?'<p class="reading-note">Des allégations d’étiquetage et des concentrations figurent dans une monographie réglementaire canadienne. Elles ne sont pas une démonstration clinique indépendante d’efficacité pour cette huile commerciale.</p>':o.clinicalStudies?.length?'<p class="reading-note">Un ou plusieurs essais cliniques originaux sont décrits plus haut. Leur résultat et leurs limites sont propres à la préparation, à la population et au protocole étudiés ; une efficacité générale n’est pas établie.</p>':'<p class="unknown">Les usages de cette fiche n’ont pas encore été recoupés de façon indépendante.</p>'}<p class="reading-note">Les données de monographie concernent une préparation définie et ne s’appliquent pas automatiquement à tous les produits.</p></section>
 <section class="sources" id="sources" hidden><h3>Les sources, en toute transparence</h3><ol>${o.sourceIds.map(id=>{const s=data.sources[id];return `<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a><span class="source-type">${esc(s.type)}${id.startsWith('hippocratus')?` · page(s) ${esc((o.sourcePages?.[id]||[o.coursePage]).join(', '))} · connexion requise`:''} · consulté le ${date(s.consulted)}</span></li>`;}).join('')}</ol><p class="reading-note">Fiche mise à jour le ${date(o.reviewedAt)}. Les illustrations sont décoratives et ne constituent pas une clé d’identification.</p></section><a class="back-catalog" href="#catalog">↑ Revenir aux plantes</a></div>`;
}
function catalogBadge(o){if(o.canadaExclusion)return 'Restriction canadienne';if(o.safetyNotice)return 'Vigilance EMA';if(o.riskSignals?.bleeding)return 'Vigilance Anses';if(o.verifiedUses?.length)return 'Usage EMA documenté';if(o.canadaUses?.length)return 'Allégation canadienne';if(o.clinicalStudies?.length)return 'Essai clinique à confirmer';if(o.status==='partial')return 'Sources recoupées';if(o.status==='institutional')return 'Source institutionnelle';return isNew(o)?'Relevé Hippocratus':'';}
function renderList(list){
 $('count').textContent=`${list.length} fiche${list.length===1?'':'s'}`;$('clear').hidden=!search.value;$('favorite-count').textContent=favorites.size;
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));
 document.querySelectorAll('[data-evidence]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.evidence===evidenceFilter)));
 $('reset-filters').disabled=!(search.value||domain.value||view!=='all'||risk||evidenceFilter);
 document.querySelector('label[for="domain"]').textContent=evidenceFilter?'Par indication documentée':'Par domaine cité';
 $('discover').disabled=list.length===0;
 document.querySelectorAll('[data-risk]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.risk===risk));});
 results.innerHTML=list.length?list.map(o=>`<button class="oil-item" type="button" data-id="${esc(o.id)}" aria-pressed="${o.id===selected}" aria-controls="detail"><img class="oil-thumb" src="${art(o)}" alt="" width="50" height="55" loading="lazy"><span class="oil-text"><strong>${esc(o.name)}${favorites.has(o.id)?' <span aria-label="Favori">★</span>':''}</strong><em>${esc(o.botanical)}</em>${catalogBadge(o)?`<small>${catalogBadge(o)}</small>`:''}</span></button>`).join(''):`<div class="empty"><strong>${view==='favorites'&&!favorites.size?'Votre herbier personnel':'Aucun résultat'}</strong>${view==='favorites'&&!favorites.size?'Ouvrez une fiche et touchez « Garder en favori » pour la retrouver ici.':risk?'Aucun signal documenté pour cette sélection. Cela ne signifie pas une absence de risque.':'Essayez moins de mots ou un autre domaine.'}<button type="button" data-reset>Voir toutes les plantes</button></div>`;
}
function render(){const list=filtered();if(!list.some(o=>o.id===selected))selected=list[0]?.id||'';updateHash();renderList(list);showDetail(oils.get(selected));}
function openOil(id,focus){selected=id;updateHash();renderList(filtered());showDetail(oils.get(id));if(focus){$('oil-title').focus({preventScroll:true});if(matchMedia('(max-width:700px)').matches)detail.scrollIntoView({behavior:reduceMotion.matches?'auto':'smooth',block:'start'});}}
function reset(){search.value='';domain.value='';view='all';risk='';evidenceFilter='';render();}
results.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openOil(b.dataset.id,true);});
document.addEventListener('click',e=>{if(e.target.closest('[data-reset]')){reset();search.focus();}});
document.querySelectorAll('[data-risk]').forEach(b=>b.addEventListener('click',()=>{risk=b.dataset.risk;render();if(!filtered().length)announce('Aucun signal documenté dans cette sélection ; cela ne signifie pas une absence de risque.');}));
document.querySelectorAll('[data-evidence]').forEach(b=>b.addEventListener('click',()=>{evidenceFilter=evidenceFilter===b.dataset.evidence?'':b.dataset.evidence;render();}));
$('reset-filters').addEventListener('click',()=>{reset();search.focus();});
search.addEventListener('input',render);domain.addEventListener('change',render);
$('clear').addEventListener('click',()=>{search.value='';render();search.focus();});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;render();}));
$('discover').addEventListener('click',()=>{const list=filtered();const other=list.filter(o=>o.id!==selected);const pool=other.length?other:list;if(!pool.length)return;const o=pool[Math.floor(Math.random()*pool.length)];openOil(o.id,true);announce(`À découvrir : ${o.name}`);});
detail.addEventListener('click',e=>{const b=e.target.closest('.source-toggle');if(!b)return;const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));b.textContent=open?'Masquer les sources':'Afficher les sources';detail.classList.toggle('sources-visible',open);$('sources').hidden=!open;if(open)$('sources').scrollIntoView({behavior:reduceMotion.matches?'auto':'smooth',block:'start'});});
detail.addEventListener('click',e=>{const b=e.target.closest('#favorite');if(!b)return;const o=oils.get(selected);if(!o)return;const added=!favorites.has(o.id);if(added)favorites.add(o.id);else favorites.delete(o.id);const saved=saveFavorites();render();if($('favorite'))$('favorite').focus({preventScroll:true});else document.querySelector('[data-view="all"]').focus();announce(saved?(added?'Ajouté à vos favoris sur cet appareil':'Retiré des favoris'):'Favoris conservés pour cette session uniquement');});
detail.addEventListener('click',e=>{const b=e.target.closest('[data-open-oil]');if(!b||!oils.has(b.dataset.openOil))return;search.value='';domain.value='';view='all';risk='';evidenceFilter='';openOil(b.dataset.openOil,true);});
$('home').addEventListener('click',e=>{e.preventDefault();reset();selected='lavande-vraie';render();window.scrollTo({top:0,behavior:reduceMotion.matches?'auto':'smooth'});});
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(oils.has(id)){search.value='';domain.value='';view='all';risk='';evidenceFilter='';selected=id;render();}});
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a||a.id==='home')return;const target=document.getElementById(a.getAttribute('href').slice(1));if(!target)return;e.preventDefault();target.scrollIntoView({behavior:reduceMotion.matches||document.body.classList.contains('motion-paused')?'auto':'smooth',block:'start'});if(target.matches('input,button'))target.focus({preventScroll:true});});
render();
})();
